name: Aggressive Keep-Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        endpoint: ['/', '/health']
    steps:
      - name: Ping Endpoint ${{ matrix.endpoint }}
        run: |
          echo "🔄 Pinging https://metameal-backend.onrender.com${{ matrix.endpoint }}"
          for i in {1..3}; do
            if curl -s --max-time 30 https://metameal-backend.onrender.com${{ matrix.endpoint }}; then
              echo "✅ Success on attempt $i"
              break
            else
              echo "⚠️ Attempt $i failed, retrying..."
              sleep 10
            fi
          done
